# application.yml
app:
  file:
    upload:
      max-size: 10485760
      allowed-types:
        - image/jpeg
        - image/jpg
        - image/png
        - image/gif
        - image/webp
        - application/pdf
      storage:
        mode: local # local, oss, minio
        local:
          base-path: /data/uploads
          base-url: http://localhost:8080/nginx
          access-prefix: /uploads/**
        oss:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          bucket-name: your-bucket
          access-key-id: your-access-key
          access-key-secret: your-secret
          domain: https://your-bucket.oss-cn-hangzhou.aliyuncs.com
        minio:
          endpoint: http://localhost:9000
          bucket-name: uploads
          access-key: minioadmin
          secret-key: minioadmin
          domain: http://localhost:9000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB