CREATE TABLE IF NOT EXISTS `transation_test`(
`id` INT UNSIGNED AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`code` VARCHAR(40) NOT NULL,
`age` int,
PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;