spring:
  redis:
    host: 127.0.0.1
    port: 6379

redisson:
  config:
    singleServerConfig:
      address: "redis://127.0.0.1:6379"
      connectionPoolSize: 32
      connectionMinimumIdleSize: 8