server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://192.168.209.128:3306/maltcloud?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: '123456'
    driver-class-name: com.mysql.jdbc.Driver