server:
  port: 9001


spring:
  datasource:
    url: jdbc:mysql://39.102.60.114:3306/maltcloud?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: '123456'
    driver-class-name: com.mysql.jdbc.Driver